services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-illchangeitanyway}
    depends_on:
      - prometheus
    ports:
      - '3000:3000'

  app:
    container_name: promgraf-nodejs-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '9200:9200'
    entrypoint: ["node"]
    command: 'index.js'

volumes:
  prometheus_data:
    name: prometheus-data
  grafana_data:
    name: grafana-data

networks:
  default:
    name: promgraf-net
